### ISSUE TITLE
Another issue for the dummie mod

### ISSUE THREAD

**Issue by CoolGuyWithAPen** [WackyModer/Bopl_Mods#4]
At the end of the game when it shows everyones scores, it only shows the winner

**Comment by WackyModer** [comment]
The dummies aren't real players, so I can't really show their score.

**Comment by Antimality** [comment]
I believe he intended to say that if you play with more than one player, the winner screen only shows the winning player on the bottom right, and non of the losers.
I can provide a screenshot if you need.

I tested this on local, and haven't checked with more than 2.
